# Generated by Django 5.0.1 on 2024-01-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_c_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='c_image',
            new_name='image',
        ),
    ]
