# Generated by Django 5.0.1 on 2024-04-17 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_community_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='communities_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
