# Generated by Django 5.0.1 on 2024-04-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_communitypost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityPost',
        ),
    ]
