# Generated by Django 5.0.1 on 2024-04-17 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_communitypost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ManyToManyField(related_name='likes', to='community.communitypost')),
            ],
        ),
    ]
