# Generated by Django 5.0.1 on 2024-03-07 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_bio_customuser_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='community',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
